In [1]:
from extract import instaExtraction
from load import get_conn

In [2]:
engine = get_conn()
m,p = instaExtraction(('talent','Wexpand Talent'),engine)

In [3]:
m

,date,followersGained,accountsEngaged,engagements,impressions,account_id,engagementRate
0,2026-06-24,0,NaN,NaN,NaN,5,NaN
1,2026-06-25,0,1.0,1.0,233.0,5,0.004292

In [4]:
p

,postId,date,postText,postUrl,postType,reactions,comments,saves,shares,engagements,impressions,avgWatchTimeMs,watchTimeMs,account_id,engagementRate,views
0,17896582380471779,2026-06-24 17:16:00+00:00,Evaluando CVs por una reclutadora Pt2 😉💙\n\nTr...,https://www.instagram.com/reel/DZ-f2brgvX8/,VIDEO,1,0,0,0.0,1,109,4827.0,497186.0,5,0.009174,109
1,18109854379745124,2026-06-23 19:03:38+00:00,¿En tu empresa se prioriza el espacio de traba...,https://www.instagram.com/p/DZ8H9m_CTVR/,CAROUSEL_ALBUM,6,0,0,NaN,7,152,NaN,NaN,5,0.046053,152
2,18127172500722570,2026-06-22 21:12:14+00:00,El departamento más adorable de Wexpand. 🐶💼\n\...,https://www.instagram.com/p/DZ5x5PDgTrP/,CAROUSEL_ALBUM,56,10,0,NaN,90,2797,NaN,NaN,5,0.032177,2797
3,18027127355821937,2026-06-18 20:13:45+00:00,🎮 LEVEL 0: The Tutorial\n\nLes presentamos Car...,https://www.instagram.com/p/DZvYA28Cf73/,CAROUSEL_ALBUM,8,0,1,NaN,10,227,NaN,NaN,5,0.044053,227
4,17852907258696726,2026-06-16 17:25:21+00:00,Grabando la oficina como si fuera…¿la oficina?...,https://www.instagram.com/reel/DZp6_pvBzsK/,VIDEO,22,0,0,5.0,28,533,17339.0,6398431.0,5,0.052533,533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,17978954083426105,2021-12-22 18:18:33+00:00,"As Nearshoring gains importance, we share that...",https://www.instagram.com/p/CXy39gygNbo/,IMAGE,4,0,0,NaN,4,0,NaN,NaN,5,0.000000,0
123,18272868370013020,2021-12-17 17:47:06+00:00,"Every business is unique, but all can benefit ...",https://www.instagram.com/p/CXl8YxiFWZ_/,IMAGE,4,0,0,NaN,4,0,NaN,NaN,5,0.000000,0
124,17864145995644059,2021-12-17 17:17:11+00:00,These days candidates look for a company with ...,https://www.instagram.com/p/CXl49oNA0wy/,IMAGE,2,0,0,NaN,2,0,NaN,NaN,5,0.000000,0
125,18204407134189391,2021-12-17 17:16:04+00:00,The labor market has changed! Find out some ti...,https://www.instagram.com/p/CXl41cqgdMP/,IMAGE,3,0,0,NaN,3,0,NaN,NaN,5,0.000000,0
126,17953015444540651,2021-12-17 17:14:05+00:00,"Nowadays, remote work is real life. We are you...",https://www.instagram.com/p/CXl4m7hgnB_/,IMAGE,5,0,0,NaN,5,0,NaN,NaN,5,0.000000,0